services:
  learning-center-platform-os:
    image: propgms-platform:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVERPASSWORD=${SERVERPASSWORD}